language: perl
perl:
  - '5.10'
  - '5.12'
  - '5.14'
  - '5.16'
  - '5.18'

before_install:
    - cpanm Test::UsedModules
    - cpanm -n git://github.com/kan/coveralls-perl.git

script: 
  - cover -test

after_success:
  - cover -report coveralls

notifications:
  recipients:
    - travis-ci.org@azumakuniyuki.org
  email:
    on_success: change
    on_failure: always
