language: perl
perl:
  - '5.10'
  - '5.12'
  - '5.14'
  - '5.16'
  - '5.18'

before_install:
    - cpanm Test::UsedModules

notifications:
  recipients:
    - travis-ci.org@azumakuniyuki.org
  email:
    on_success: change
    on_failure: always
